### ISSUE TITLE
Update to JDepend 2.10

### ISSUE THREAD

**Issue by sfo** [mojohaus/jdepend-maven-plugin#6]
Two month ago, [JDepend 2.10 has been released](https://github.com/clarkware/jdepend/releases/tag/2.10). It would be great to see a new release of the plugin as well since the new version improves Java 8 support.

**Comment by xiaozhiliaoo** [comment]
@sfo  is jdepend-maven-plugin still not support java8？

**Comment by jiangxincode** [comment]
I have update JDepend versions, not it can support Java 8.
<https://github.com/jiangxincode/jdepend-maven-plugin/commit/e9e4db3c303ebdc23360732806b7cbb7e28b5c57>
